<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">

<!--<!DOCTYPE students [
		<!ELEMENT students (student*) > &lt;!&ndash;“ * ”表示student出现0次或多次，“ + ”表示至少一次&ndash;&gt;
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>
		]>
-->

<!--DTD：
	引入dtd文档到xml文档中
		内部dtd：将约束规则定义在xml文档中
		外部dtd：将约束的规则定义在外部的dtd文件中
			本地：<!DOCTYPE 根标签名 SYSTEM "dtd文件的位置">
			网络：<!DOCTYPE 根标签名 PUBLIC "dtd文件名字" "dtd文件的位置URL">
-->

<students>

	<student number="s01">
		<name>Adam</name>
		<age>20</age>
		<sex>male</sex>
	</student>

	<student number="s02">
		<name>Tom</name>
		<age>21</age>
		<sex>male</sex>
	</student>

</students>